site_name: Terratags
site_description: A tool for validating tags on AWS resources in Terraform configurations
site_url: https://terratags.github.io/terratags/
repo_url: https://github.com/terratags/terratags
repo_name: terratags/terratags

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - attr_list
  - md_in_html

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration:
    - Required Tags: configuration.md
    - Exemptions: exemptions.md
    - Default Tags: default-tags.md
  - Usage: usage.md
  - CI/CD Integration: ci-cd.md
  - Examples: examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terratags/terratags
  generator: false